# Generated by Django 5.1.5 on 2025-01-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('assistant_manager', 'Assistant Manager'), ('team_leader', 'Team Leader'), ('employee', 'Employee')], max_length=20, null=True),
        ),
    ]
