# Generated by Django 5.1.5 on 2025-02-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_notification_user_notification_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='payment_method',
            field=models.CharField(choices=[('check', 'Check'), ('cash', 'Cash'), ('bank', 'Bank')], max_length=50),
        ),
    ]
