# Generated by Django 5.1.5 on 2025-02-13 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_salary_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepaymentrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='advancepaymentrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='advancepaymentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
