# Generated by Django 5.1.5 on 2025-02-13 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_advancepaymentrequest_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advancepaymentrequest',
            old_name='employee',
            new_name='user',
        ),
    ]
