# Generated by Django 5.1.5 on 2025-02-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_employee_advancepaymentrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee'), ('assistant manager', 'Assistant Manager')], max_length=50, null=True),
        ),
    ]
