# Generated by Django 5.1.5 on 2025-02-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=90, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Manager'), ('assistant_manager', 'Assistant Manager'), ('team_leader', 'Team Leader'), ('employee', 'Employee')], max_length=20, null=True),
        ),
    ]
