# Generated by Django 5.1.5 on 2025-02-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee'), ('assistant manager', 'Assistant Manager'), ('team leader', 'Team Leader')], max_length=50, null=True),
        ),
    ]
