# Generated by Django 5.1.5 on 2025-02-12 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdvancePaymentRequest',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Payroll',
        ),
    ]
