# Generated by Django 5.1.5 on 2025-02-12 06:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_user_hourly_rate_user_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollrecord',
            old_name='deductions',
            new_name='advance_taken',
        ),
        migrations.RenameField(
            model_name='payrollrecord',
            old_name='net_pay',
            new_name='final_amount',
        ),
        migrations.RenameField(
            model_name='payrollrecord',
            old_name='tax',
            new_name='tax_deducted',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='date',
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter a positive value for extra pay or a negative value for fines', max_digits=7),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='The scheduled date for payment each month'),
            preserve_default=False,
        ),
    ]
