# Generated by Django 5.1.5 on 2025-02-12 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_deductions_payrollrecord_advance_taken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='user',
            name='payment_schedule',
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('direct_deposit', 'Direct Deposit'), ('check', 'Check'), ('electronic_transfer', 'Electronic Transfer')], max_length=50)),
                ('payday', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PayrollRecord',
        ),
    ]
