# Generated by Django 5.1.5 on 2025-02-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_user_hourly_rate_remove_user_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salary',
            name='payment_method',
            field=models.CharField(default='bank_transfer', max_length=50),
        ),
        migrations.AddField(
            model_name='salary',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
